# Generated by Django 2.2.5 on 2019-10-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyanru', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
