# Generated by Django 2.2.6 on 2019-10-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
