# Generated by Django 2.2.5 on 2019-10-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0002_auto_20191006_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='purchase_date',
        ),
    ]
