# Generated by Django 2.2.5 on 2019-10-06 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0004_bookdata_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
