# Generated by Django 2.2.5 on 2019-10-06 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0007_remove_bookdata_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
