# Generated by Django 2.2.5 on 2019-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0008_bookdata_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='purchase_date',
        ),
    ]
