# Generated by Django 2.2.5 on 2019-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkanri', '0011_remove_bookdata_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
